### PR TITLE
fix: let the platform decide for login and registration

### PR DESCRIPTION
**Pull request by CodeWithEmad**
This will 

- Removes the force to using authn mfe for login and registration
- Removes trailing whitespaces
- Fixes some typos

### CODE REVIEW

**Comment by hinakhadim** [comment]
Thanks for the PR.  I have tested with normal auth flow and it's working fine.  Could you please elaborate on the following questions related to tpa:

- For the third-party auth logic, if I added the tpa slug, will it take me to the tpa page directly?
- Why is there a need to add tpa in authn mfe when one can directly go to the tpa page?

If you can share a working video of it with TPA, it will greatly help me understand the flow with TPA. or let me know how to test tpa on my system. For now, I've added `FEATURES['THIRD_PARTY_AUTH_HINT'] = 'oa2-google'` in settings.  But unable to test TPA flow as I am expecting that there will be more configurations to setup.

**Comment by CodeWithEmad** [comment]
> For the third-party auth logic, if I added the tpa slug, will it take me to the tpa page directly?

Yes, you can test if you have a TPA setup and add  `"THIRD_PARTY_AUTH_HINT": "some-provider-slug",` inside SiteConfiguration (it takes up to 3 minutes to update because of the cache) or have it directly in settings with a plugin.

> Why is there a need to add tpa in authn mfe when one can directly go to the tpa page?

I don't get it. OpenedX covers all sorts of scenarios and all of them are handled with login/register views. in this scenario, it's not possible if you want users to not interact with authn mfe and use your desired TPA directly (Good UX). Instead, you need to let them know that after login, you need to click on another button to login (Bad UX)


Here is a video of SAML login setup on one of our test orgs.
[Screencast from 06-14-2024 02:12:27 PM.webm](https://github.com/overhangio/tutor-indigo/assets/49523567/5d7f8625-a174-4345-8298-e5499134658f)

**Comment by hinakhadim** [comment]
Awesome! Thanks a lot for sharing the video. It clears things up much better.

I'll appreciate it if you could do the below tasks in this PR.

1. Move the Register button condition before signing in button. It is better to place the sign-in button after the register button.
2. Add a changelog entry.

**Comment by CodeWithEmad** [comment]
No Problem.

**Review by hinakhadim — APPROVED** [review]

**Pull request merged**
