### PR TITLE
fix: footer date

### LINKED ISSUE #62: Copyright Year hard-coded to 2023
https://github.com/overhangio/tutor-indigo/blob/188cb63edb2766b35a4aa84ea43180e3bcacba3e/tutorindigo/templates/indigo/lms/templates/footer.html#L55

https://github.com/overhangio/tutor-indigo/blob/188cb63edb2766b35a4aa84ea43180e3bcacba3e/tutorindigo/templates/indigo/lms/templates/footer.html#L119

Screenshot from 2024-02-18 15-49-34

### PR DESCRIPTION
**Pull request by CodeWithEmad**
This will:

- fix the hardcoded year in the footer.
- Update the URL of tutor docs.
- A new screenshot inside README.
- Cleanup in README.rst (correct Open edX URL and mako code highlighting)

Close #62 #64

### CODE REVIEW

**Comment by misilot** [comment]
I don't think this will fix the hard coded date on the MFE apps domain (and others?)

https://apps.sandbox.openedx.edly.io/learner-dashboard/

**Comment by CodeWithEmad** [comment]
I don't get it. Why not?

**Comment by misilot** [comment]
At least from what I am seeing is the Apps MFE does not inherit settings from Indigo, though it uses parts of it (like links to the logos) such as the color or footer settings. Maybe it's something broken with my forked theme, but it is something to check.

**Comment by misilot** [comment]
Yeah, 99% it comes from this https://github.com/edly-io/frontend-component-footer/blob/quince/indigo/src/components/Footer.messages.js#L159-L163

**Comment by hinakhadim** [comment]
Thanks for the PR. Let me make sure, everything is working for merging. Also, It won't update the MFE footer year because it's hard-coded in MFE footer.

**Comment by CodeWithEmad** [comment]
You're right, @misilot. I didn't notice the new changes in Quince:
`RUN npm install '@edx/frontend-component-footer@npm:@edly-io/indigo-frontend-component-footer@^1.0.0'`
and only checked the https://github.com/openedx/frontend-component-footer, couldn't find any hardcoded thing there and suspected the indigo theme. should I close this?
Also, Is there any documentation about the new changes coming from edly-io?

**Comment by hinakhadim** [comment]
@CodeWithEmad Thanks for the PR.

**Pull request merged**
